language: bash

env:
  - BASH=latest
  - BASH=5.0.3
  - BASH=4.4.23
before_script: 
  - docker pull bash:$BASH
  - docker run bash:$BASH --version
script:
  - docker run -v $PWD:/bash bash:$BASH bash/test_assert.sh
